name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.12"]
        exclude:
          - os: macos-latest
            python-version: "3.8"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install ".[test]"
      - run: pytest -q
      - run: cosegvcf --vcf examples/FATHER.vcf examples/MOTHER.vcf examples/PROBAND.vcf examples/SISTER.vcf --ped examples/family.ped --model AR_ANY -o example_out.vcf
